name: study_platform
description: Study Platform app for my bachelor's thesis.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.10.6
  firebase_core_web: ^1.5.3
  firebase_auth: ^3.3.4
  firebase_storage: ^10.2.4
  cloud_firestore: ^3.1.5
  cloud_firestore_web: ^2.6.5
  flutter_bloc: ^8.0.0
  bloc_test: ^9.0.1
  test: ^1.19.5
  equatable: ^2.0.3
  formz: ^0.4.1
  mocktail: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true
