name: study_platform
description: Study Platform app for my bachelor's thesis.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^8.3.0
  universal_html: ^2.0.8
  file_picker: ^4.3.0
  path_provider: ^2.0.8
  flutter_widget_from_html: ^0.8.4
  flutter_widget_from_html_core: ^0.8.4
  html_editor_enhanced: ^2.4.0+1
  enum_to_string: ^2.0.1
  json_annotation: ^4.4.0
  cupertino_icons: ^1.0.4
  firebase_core: ^1.10.6
  firebase_core_web: ^1.5.3
  firebase_auth: ^3.3.4
  firebase_storage: ^10.2.4
  cloud_firestore: ^3.1.5
  cloud_firestore_web: ^2.6.5
  flutter_bloc: ^8.0.1
  bloc_test: ^9.0.2
  test: ^1.19.5
  equatable: ^2.0.3
  formz: ^0.4.1
  mocktail: ^0.2.0


dev_dependencies:
  build_runner:
  freezed: ^1.1.0
  json_serializable: ^6.1.3

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - images/